### ISSUE TITLE
Not running on linux Mint 18.3

### ISSUE THREAD

**Issue by fiti7** [BoredLama/stremio-open-directories-addon#1]
i tried to run it b double click and used terminal I got this error:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::7000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Addon.module.exports.runHTTPWithOptions (/snapshot/stremio-open-directories-addon/node_modules/stremio-addon-sdk/index.js:86:10)
    at Object.<anonymous> (/snapshot/stremio-open-directories-addon/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)

**Comment by jaruba** [comment]
check the readme, after u run it, a config.json file is created in the same folder, u can change the 7000 port to some other port from there

**Comment by BoredLama** [comment]
jaruba is right, you can change the port from `config.json`

I made a new release now that changes the port to `7005`, so it doesn't use the same port as the jackett add-on anymore.
